---
- name: Converge
  hosts: all
  #become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'

  roles:
    - role: geerlingguy.git
    - role: geerlingguy.dotfiles
